### ISSUE TITLE
Clarify further communication

### ISSUE THREAD

**Issue by konraifen88** [konraifen88/dkx50q#1]
I think we should clarify on how we communicate together about the dos and don'ts of the project.

I my eyes we have the following possibilities:
|          | Pro                                                | Con                               |
|----------|----------------------------------------------------|-----------------------------------|
| Forum    | ???                                                | * Not open to everyone            |
| Mail     | * Easy to answer                                   | * Not open to everyone            |
| GH Isues | * Open communication <br>* Communication near the code | * Maybe not that handy than mails |

@shaun-lloyd what do you think?

**Comment by shaun-lloyd** [comment]
All docs / communication through github issue or documentation in github.

Any email content that is relevant should be added in documentation / code / issue.

**Comment by konraifen88** [comment]
Sounds fine for me, shall we create a discord server and use discord instead of email?

**Comment by shaun-lloyd** [comment]
email my preferred. This really shouldn't take that long. I'm juggling a few projects at the moment just not huge priority.
