### ISSUE TITLE
Own driver required?

### ISSUE THREAD

**Issue by konraifen88** [konraifen88/dkx50q#2]
I'm not sure if we would need an own driver for controlling the backlight of the keyboard. I think it would be easier to have a simple python project talking to the USB prot directly using the libusb package.

I see as a drawback of using a driver, that we have to handle all key presses, too.

**Comment by shaun-lloyd** [comment]
Agreed. The code as is represents this.

**Comment by konraifen88** [comment]
Yeah, you are right, I should have looked into it better.

**Comment by lupettohf** [comment]
Hi, sorry for reopening this, a good idea would be to update the existing https://github.com/octo/das/ go interface

**Comment by shaun-lloyd** [comment]
Thank you so much. I had no idea the interface existed. I'll check it out and get back to youOn 18 Jan 2021 3:52 am, Andrea Santaniello <notifications@github.com> wrote:
Hi, sorry for reopening this, a good idea would be to update the existing https://github.com/octo/das/ go interface

**Comment by lupettohf** [comment]
There is also a node interface. All are using libusb, I want to work on this too, it's a shame that such a keyboard does not work on linux or osx.
