### ISSUE TITLE
How to setup requirements.txt

### ISSUE THREAD

**Issue by konraifen88** [konraifen88/dkx50q#3]
Hey @shaun-lloyd can you please document how to use the `requirements.txt` you've added to the project? I've tried the way I knew to install the dependencies but the file could not be read.

Using `pip install -r requirements.txt` fails as the format seems to be not readable. I've installed the requirements rewriting the file to the format: `dependency==version`.

**Comment by shaun-lloyd** [comment]
source venv/bin/activate.
pip install -r requirements.txt

**Comment by shaun-lloyd** [comment]
cd src/
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
./connect.py

**Comment by shaun-lloyd** [comment]
i just fixed the requirements.txt, no idea how i did that. My bad. all good to go now.

**Comment by konraifen88** [comment]
Ok, this looks better now :+1: 
Did not know if you are using some special version of requirements.txt

**Comment by shaun-lloyd** [comment]
nah i just honestly fucked up.
